//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VATUE2Lib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VATUE2Lib.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A. MIEJSCE SKŁADANIA INFORMACJI.
        /// </summary>
        internal static string ContainerTitleA {
            get {
                return ResourceManager.GetString("ContainerTitleA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B. DANE PODATNIKA.
        /// </summary>
        internal static string ContainerTitleB {
            get {
                return ResourceManager.GetString("ContainerTitleB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.1. DANE IDENTYFIKACYJNE.
        /// </summary>
        internal static string ContainerTitleB1 {
            get {
                return ResourceManager.GetString("ContainerTitleB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.2. ADRES ZAMIESZKANIA.
        /// </summary>
        internal static string ContainerTitleB2A {
            get {
                return ResourceManager.GetString("ContainerTitleB2A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.2. ADRES SIEDZIBY.
        /// </summary>
        internal static string ContainerTitleB2B {
            get {
                return ResourceManager.GetString("ContainerTitleB2B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C. INFORMACJA O WEWNĄTRZWSPÓLNOTOWYCH DOSTAWACH TOWARÓW.
        /// </summary>
        internal static string ContainerTitleC {
            get {
                return ResourceManager.GetString("ContainerTitleC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D. INFORMACJA O WEWNĄTRZWSPÓLNOTOWYCH NABYCIACH TOWARÓW.
        /// </summary>
        internal static string ContainerTitleD {
            get {
                return ResourceManager.GetString("ContainerTitleD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E. INFORMACJA O WEWNĄTRZWSPÓLNOTOWYM ŚWIADCZENIU USUŁUG.
        /// </summary>
        internal static string ContainerTitleE {
            get {
                return ResourceManager.GetString("ContainerTitleE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F. OŚWIADCZENIE PODATNIKA LUB OSOBY REPREZENTUJĄCEJ PODATNIKA.
        /// </summary>
        internal static string ContainerTitleF {
            get {
                return ResourceManager.GetString("ContainerTitleF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podstawa prawna:.
        /// </summary>
        internal static string InfoContent0Label {
            get {
                return ResourceManager.GetString("InfoContent0Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art.100 ustawy z dnia 11 marca 2004 r. o podatku od towarów i usług (Dz. U. Nr 54, poz.535, z późn. zm.), zwanej dalej &quot;ustawą&quot;..
        /// </summary>
        internal static string InfoContent0Value {
            get {
                return ResourceManager.GetString("InfoContent0Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Składający:.
        /// </summary>
        internal static string InfoContent1Label {
            get {
                return ResourceManager.GetString("InfoContent1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podatnicy podatku od towaór i usług oraz osoby prawne niebędące podatnikami w rozumieniu art. 15 ustawy - zarejestrowani jako podatnicy VAT UE, dokonujący wewnątrzwspólnotowej dostawy towarów, wewnątrzwspólnotowego nabycia towarów lub wewnątrzwpólnotowego swiadczenia usuług..
        /// </summary>
        internal static string InfoContent1Value {
            get {
                return ResourceManager.GetString("InfoContent1Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termin składania:.
        /// </summary>
        internal static string InfoContent2Label {
            get {
                return ResourceManager.GetString("InfoContent2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do 15 dnia miesiąca po okresie, za który składana jest informacja..
        /// </summary>
        internal static string InfoContent2Value {
            get {
                return ResourceManager.GetString("InfoContent2Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miejsce składania:.
        /// </summary>
        internal static string InfoContent3Label {
            get {
                return ResourceManager.GetString("InfoContent3Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podatnicy, o których mowa w art. 15 ustawy, składają informację do urzędu skarbowego właściwego ze względu na miejsce wykonania czynności podlegających opodatkowaniu podatkiem od towarów i usług, a jeżeli czynności te wykonywane są na terenie dwóch lub więcej urzędów skarbowych, to osoby fizyczne składją ją w urzędzie skarbowym właściwym ze względu na miejsce zamieszkania, a osoby prawne i jednostki organizacyjne niemające osobowści prawnej - ze względu na dres siedziby. Podatnicy nieposiadający stałego mie [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InfoContent3Value {
            get {
                return ResourceManager.GetString("InfoContent3Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Numer Identyfikacji Podatkowej podatnika.
        /// </summary>
        internal static string InputTitle1 {
            get {
                return ResourceManager.GetString("InputTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10. Kraj.
        /// </summary>
        internal static string InputTitle10 {
            get {
                return ResourceManager.GetString("InputTitle10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11. Województwo.
        /// </summary>
        internal static string InputTitle11 {
            get {
                return ResourceManager.GetString("InputTitle11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12. Powiat.
        /// </summary>
        internal static string InputTitle12 {
            get {
                return ResourceManager.GetString("InputTitle12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13. Gmina.
        /// </summary>
        internal static string InputTitle13 {
            get {
                return ResourceManager.GetString("InputTitle13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14. Ulica.
        /// </summary>
        internal static string InputTitle14 {
            get {
                return ResourceManager.GetString("InputTitle14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15. Nr domu.
        /// </summary>
        internal static string InputTitle15 {
            get {
                return ResourceManager.GetString("InputTitle15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16. Nr lokalu.
        /// </summary>
        internal static string InputTitle16 {
            get {
                return ResourceManager.GetString("InputTitle16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17. Miejscowość.
        /// </summary>
        internal static string InputTitle17 {
            get {
                return ResourceManager.GetString("InputTitle17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18. Kod pocztowy.
        /// </summary>
        internal static string InputTitle18 {
            get {
                return ResourceManager.GetString("InputTitle18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19. Poczta.
        /// </summary>
        internal static string InputTitle19 {
            get {
                return ResourceManager.GetString("InputTitle19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Nr dokumentu.
        /// </summary>
        internal static string InputTitle2 {
            get {
                return ResourceManager.GetString("InputTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20. Imie.
        /// </summary>
        internal static string InputTitle20 {
            get {
                return ResourceManager.GetString("InputTitle20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21. Nazwisko.
        /// </summary>
        internal static string InputTitle21 {
            get {
                return ResourceManager.GetString("InputTitle21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22. Telefon kontaktowy.
        /// </summary>
        internal static string InputTitle22 {
            get {
                return ResourceManager.GetString("InputTitle22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23. Data wypelnenia.
        /// </summary>
        internal static string InputTitle23 {
            get {
                return ResourceManager.GetString("InputTitle23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24. Podpis (i pieczątka) podatnika lub osoby reprezentującej podatnika.
        /// </summary>
        internal static string InputTitle24 {
            get {
                return ResourceManager.GetString("InputTitle24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Status.
        /// </summary>
        internal static string InputTitle3 {
            get {
                return ResourceManager.GetString("InputTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Miesiąc.
        /// </summary>
        internal static string InputTitle4 {
            get {
                return ResourceManager.GetString("InputTitle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Kwartał.
        /// </summary>
        internal static string InputTitle5 {
            get {
                return ResourceManager.GetString("InputTitle5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. Rok.
        /// </summary>
        internal static string InputTitle6 {
            get {
                return ResourceManager.GetString("InputTitle6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7. Urząd skarbowy, do którego adresowana jest informacja.
        /// </summary>
        internal static string InputTitle7 {
            get {
                return ResourceManager.GetString("InputTitle7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8. Rodzaj podatnika.
        /// </summary>
        internal static string InputTitle8 {
            get {
                return ResourceManager.GetString("InputTitle8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Podatnik niebędący osobą fizyczną.
        /// </summary>
        internal static string InputTitle81 {
            get {
                return ResourceManager.GetString("InputTitle81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Osoba fizyczna.
        /// </summary>
        internal static string InputTitle82 {
            get {
                return ResourceManager.GetString("InputTitle82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9. Nazwisko.
        /// </summary>
        internal static string InputTitle9 {
            get {
                return ResourceManager.GetString("InputTitle9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię.
        /// </summary>
        internal static string InputTitle9A {
            get {
                return ResourceManager.GetString("InputTitle9A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Urodzenia.
        /// </summary>
        internal static string InputTitle9B {
            get {
                return ResourceManager.GetString("InputTitle9B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesel.
        /// </summary>
        internal static string InputTitle9C {
            get {
                return ResourceManager.GetString("InputTitle9C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa pełna.
        /// </summary>
        internal static string InputTitle9D {
            get {
                return ResourceManager.GetString("InputTitle9D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regon.
        /// </summary>
        internal static string InputTitle9E {
            get {
                return ResourceManager.GetString("InputTitle9E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        internal static string TableHead2CellA {
            get {
                return ResourceManager.GetString("TableHead2CellA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b.
        /// </summary>
        internal static string TableHead2CellB {
            get {
                return ResourceManager.GetString("TableHead2CellB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c.
        /// </summary>
        internal static string TableHead2CellC {
            get {
                return ResourceManager.GetString("TableHead2CellC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        internal static string TableHead2CellD {
            get {
                return ResourceManager.GetString("TableHead2CellD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod kraju.
        /// </summary>
        internal static string TableHeadCellA {
            get {
                return ResourceManager.GetString("TableHeadCellA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer Identyfikacyjny VAT kontrahenta.
        /// </summary>
        internal static string TableHeadCellB {
            get {
                return ResourceManager.GetString("TableHeadCellB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kwota transakcji w zł.
        /// </summary>
        internal static string TableHeadCellC {
            get {
                return ResourceManager.GetString("TableHeadCellC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transakcje trójstronne.
        /// </summary>
        internal static string TableHeadCellD {
            get {
                return ResourceManager.GetString("TableHeadCellD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT-UE.
        /// </summary>
        internal static string TitleLabel1 {
            get {
                return ResourceManager.GetString("TitleLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFORMACJA PODSUMOWUJĄCA O DOKONANCYH WEWNĄTRZWSPÓLNOTOWYCH TRANSAKCJACH.
        /// </summary>
        internal static string TitleLabel2 {
            get {
                return ResourceManager.GetString("TitleLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUB.
        /// </summary>
        internal static string TitleLabel3 {
            get {
                return ResourceManager.GetString("TitleLabel3", resourceCulture);
            }
        }
    }
}
